name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@6bb17719bb5141a0ee798580a44343d04263d110 # 2024-06-24